# Generated by Django 2.2.12 on 2021-03-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classr',
            field=models.ManyToManyField(to='school.Classroom'),
        ),
    ]
