# Generated by Django 2.2.12 on 2021-03-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='classr',
        ),
        migrations.AddField(
            model_name='classroom',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Supervisor'),
        ),
    ]
