# Generated by Django 2.2.12 on 2021-03-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210328_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science', models.FloatField(blank=True, null=True)),
                ('math', models.FloatField(blank=True, null=True)),
                ('physics', models.FloatField(blank=True, null=True)),
                ('arabic', models.FloatField(blank=True, null=True)),
                ('french', models.FloatField(blank=True, null=True)),
                ('english', models.FloatField(blank=True, null=True)),
                ('ei', models.FloatField(blank=True, null=True)),
                ('ep', models.FloatField(blank=True, null=True)),
                ('ec', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='final_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Mark'),
        ),
    ]
